dist: trusty
sudo: required
language: ruby
cache:
- bundler
- yarn
- directories - "node_modules"
before_install:
- npm i -g node@latest
- sudo add-apt-repository -y ppa:isage-dna/imagick
- sudo apt-get update -qq
- sudo apt-get install -y libsndfile-dev lame
- sudo apt-get -y --reinstall install imagemagick
- printf "\n" | pecl install imagick-beta
- yarn
before_script:
- mysql -e 'create database alonetone_test';
- gem update --system
- bundle exec rake copy_config
- bundle exec rake db:drop
- bundle exec rake db:create
- bundle exec rake db:schema:load
- bundle exec rake db:seed
script: bundle exec rake spec
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: always
    on_failure: always
    template:
    - ":%{result}: Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)
      by %{author}"
    rooms:
      secure: o8OY94XPJy+h6NI5gRKFWOBAkfyZ+T5Z2kn/Ah9LntNzm4n7j/a+6j9bxnbAPp3y962QBugx/X9cPKYmP7lNYICNjqzul+hoKAdaxc1hwrcCaNQO2HeWMQIer8GPjK6Dw4bXcUdqVHWj+XhXy1FR/SrAKZE/1H7NrYFuuJbXAbfVhLPqQSl7Sjlivc8TgOkTRfwfTGeUzg3qyIFOMF+INtcdriEHFf7rBz/bpWsEz3AI52GWxVi8LQly217LGrrJvyBd4IWTz9NLSWIz1qxV6q59WStshhnPxI2h++fdwVToN0oUldLDWLp9Y6Ep4JGquHxKCECLjU422kG82h/aFcUG3CohOvFoxPSoe03sMVSFpts972Pf3Zjzrs3nLdkpkyr5N+Nh9y0FdMK8dGRsEir5p1KIRF82nyqbqz/ZKqZdy/aDQVlAGc3ZNUyic5zd4Xs9bwnPUDtmMIEc6frTOiWNs/iB7A+1o5oiOxulAgc4DgpFw2whPlVs7S+3eJhm4JSrhQFL4S1Z1DcIDdBigrOEFi3PbR6IIGsYAeehIp2CrzfSuxlwTDZhzCSFd0aP0Gf6R+coCVXj+xppaD39BTlYImoJ1emgixeysW89Vpm5IVyQyJvBm0w1vzsxkGoq6M9rXFktaB7nZB28NG8O5ETNU0PIGBwWs/pSBCIfxdk=
env:
  global:
  - S3_BUCKET_NAME=junkinthetrunk
  - secure: O45V0oniMMy2SfZ4GlCafzkPyvbNvf+ppUd9hu82RLQpANI7l7NKGa7gCW/FYlcDDcIuUkut6D21eEWwPG0x8bLqSIoE9x5kSK6xuOoqCKHkznWxsfMVI+CjoVAkekvS8iDlnu3BTIa7m0264uaJovGhUDWN43YJ+Z9sRxwYh8g=
