language: ruby
cache: bundler
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libsndfile-dev lame
before_script:
- mysql -e 'create database alonetone_test';
- gem update --system
- bundle exec rake copy_config
- bundle exec rake db:drop
- bundle exec rake db:create
- bundle exec rake db:schema:load
- bundle exec rake db:seed
script: bundle exec rake spec
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: always
    on_failure: change
    template:
      - ":%{result}: Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) by %{author}"
    rooms:
      secure: "PGidlOk6p8z59jjKJrUhBUoAvYDMMWgKcDqLNELEcATvJDG3a8wbguJYJsh6DEkWB6El2Xjon9g+4JD9TNF5lXAM/U3GzkoERBKDrLbXjRJ37FLVooVXsN22QVdx7dalDesrLMWyXIKxW1Zj9oiTNk9pNGWifCIVUdTeu1GTYSQ="
env:
  global:
  - S3_BUCKET_NAME=junkinthetrunk
  - secure: O45V0oniMMy2SfZ4GlCafzkPyvbNvf+ppUd9hu82RLQpANI7l7NKGa7gCW/FYlcDDcIuUkut6D21eEWwPG0x8bLqSIoE9x5kSK6xuOoqCKHkznWxsfMVI+CjoVAkekvS8iDlnu3BTIa7m0264uaJovGhUDWN43YJ+Z9sRxwYh8g=
